# Draft

In [170]:
import pandas as pd
import numpy as np


array = np.arange(10)
array_splited = np.array_split(array, np.ceil(len(array)/8))
for split in array_splited:
    print(len(split))


5
5


In [13]:
np.ceil(10/8)

2.0

# Model Informations

In [ ]:
'''
Φ: conjunto de features
P: amostras de classe 1
N: amostras de classe 0
φ: fórmula normal disjuntiva
m: número de cláusulas conjuntivas
l: número máximo de literais por cláusula
t: cada feature

w ∈ P U N
i ∈ {1, ..., m}
j ∈ {1, ..., l}
t ∈ Φ U {*}

xi,j,t = true: atômica t ocorre no j° literal da iª cláusula
pi,j = true: atômica t ocorre positivamente
pi,j = false: atômica t ocorre negativamente

xi,j,* = true: é pulado o j° literal da iª cláusula
'''

In [ ]:
'''
A, B, C | y
0, 1, 0 | 0
1, 0, 1 | 1
0, 1, 1 | 0

m = 2
l = 2

(7.5)
(x1,1,A V x1,1,B V x1,1,C V x1,1,*) ∧ 

(x1,2,A V x1,2,B V x1,2,C V x1,2,*) ∧ 

(x2,1,A V x2,1,B V x2,1,C V x2,1,*) ∧ 

(x2,2,A V x2,2,B V x2,2,C V x2,2,*)

(7.6)
(¬x1,1,A V ¬x1,1,B) ∧ (¬x1,1,A V ¬x1,1,C) ∧ (¬x1,1,A V ¬x1,1,*) ∧ 
(¬x1,1,B V ¬x1,1,C) ∧ (¬x1,1,B V ¬x1,1,*) ∧ (¬x1,1,C V ¬x1,1,*) ∧ 

(¬x1,2,A V ¬x1,2,B) ∧ (¬x1,2,A V ¬x1,2,C) ∧ (¬x1,2,A V ¬x1,2,*) ∧ 
(¬x1,2,B V ¬x1,2,C) ∧ (¬x1,2,B V ¬x1,2,*) ∧ (¬x1,2,C V ¬x1,2,*) ∧ 

(¬x2,1,A V ¬x2,1,B) ∧ (¬x2,1,A V ¬x2,1,C) ∧ (¬x2,1,A V ¬x2,1,*) ∧ 
(¬x2,1,B V ¬x2,1,C) ∧ (¬x2,1,B V ¬x2,1,*) ∧ (¬x2,1,C V ¬x2,1,*) ∧ 

(¬x2,2,A V ¬x2,2,B) ∧ (¬x2,2,A V ¬x2,2,C) ∧ (¬x2,2,A V ¬x2,2,*) ∧ 
(¬x2,2,B V ¬x2,2,C) ∧ (¬x2,2,B V ¬x2,2,*) ∧ (¬x2,2,C V ¬x2,2,*)

(7.7)
(¬x1,1,* V ¬x1,2,*) ∧ 

(¬x2,1,* V ¬x2,2,*)

(7.8)
Equivalência para deixar na FNC ---------------------------------------
xi,j,t -> (pi,j <-> di,j,w,t) ≡ 
(¬xi,j,t V ¬pi,j V di,j,w,t) ∧ (¬xi,j,t V pi,j V ¬di,j,w,t)
-----------------------------------------------------------------------
Substituição de variável condicionada aos valores do dataset ----------
di,j,w,t = 1, então usa yi,j,w
di,j,w,t = 0, então usa ¬yi,j,w
-----------------------------------------------------------------------
(¬x1,1,A V ¬p1,1 V ¬y1,1,1) ∧ (¬x1,1,A V p1,1 V y1,1,1) ∧ 
(¬x1,1,A V ¬p1,1 V y1,1,2) ∧ (¬x1,1,A V p1,1 V ¬y1,1,2) ∧ 
(¬x1,1,A V ¬p1,1 V ¬y1,1,3) ∧ (¬x1,1,A V p1,1 V y1,1,3) ∧ 

(¬x1,1,B V ¬p1,1 V y1,1,1) ∧ (¬x1,1,B V p1,1 V ¬y1,1,1) ∧ 
(¬x1,1,B V ¬p1,1 V ¬y1,1,2) ∧ (¬x1,1,B V p1,1 V y1,1,2) ∧ 
(¬x1,1,B V ¬p1,1 V y1,1,3) ∧ (¬x1,1,B V p1,1 V ¬y1,1,3) ∧ 

(¬x1,1,C V ¬p1,1 V ¬y1,1,1) ∧ (¬x1,1,C V p1,1 V y1,1,1) ∧ 
(¬x1,1,C V ¬p1,1 V y1,1,2) ∧ (¬x1,1,C V p1,1 V ¬y1,1,2) ∧ 
(¬x1,1,C V ¬p1,1 V y1,1,3) ∧ (¬x1,1,C V p1,1 V ¬y1,1,3) ∧ 

(¬x1,2,A V ¬p1,2 V ¬y1,2,1) ∧ (¬x1,2,A V p1,2 V y1,2,1) ∧ 
(¬x1,2,A V ¬p1,2 V y1,2,2) ∧ (¬x1,2,A V p1,2 V ¬y1,2,2) ∧ 
(¬x1,2,A V ¬p1,2 V ¬y1,2,3) ∧ (¬x1,2,A V p1,2 V y1,2,3) ∧ 

(¬x1,2,B V ¬p1,2 V y1,2,1) ∧ (¬x1,2,B V p1,2 V ¬y1,2,1) ∧ 
(¬x1,2,B V ¬p1,2 V ¬y1,2,2) ∧ (¬x1,2,B V p1,2 V y1,2,2) ∧ 
(¬x1,2,B V ¬p1,2 V y1,2,3) ∧ (¬x1,2,B V p1,2 V ¬y1,2,3) ∧ 

(¬x1,2,C V ¬p1,2 V ¬y1,2,1) ∧ (¬x1,2,C V p1,2 V y1,2,1) ∧ 
(¬x1,2,C V ¬p1,2 V y1,2,2) ∧ (¬x1,2,C V p1,2 V ¬y1,2,2) ∧ 
(¬x1,2,C V ¬p1,2 V y1,2,3) ∧ (¬x1,2,C V p1,2 V ¬y1,2,3) ∧ 

(¬x2,1,A V ¬p2,1 V ¬y2,1,1) ∧ (¬x2,1,A V p2,1 V y2,1,1) ∧ 
(¬x2,1,A V ¬p2,1 V y2,1,2) ∧ (¬x2,1,A V p2,1 V ¬y2,1,2) ∧ 
(¬x2,1,A V ¬p2,1 V ¬y2,1,3) ∧ (¬x2,1,A V p2,1 V y2,1,3) ∧ 

(¬x2,1,B V ¬p2,1 V y2,1,1) ∧ (¬x2,1,B V p2,1 V ¬y2,1,1) ∧ 
(¬x2,1,B V ¬p2,1 V ¬y2,1,2) ∧ (¬x2,1,B V p2,1 V y2,1,2) ∧ 
(¬x2,1,B V ¬p2,1 V y2,1,3) ∧ (¬x2,1,B V p2,1 V ¬y2,1,3) ∧ 

(¬x2,1,C V ¬p2,1 V ¬y2,1,1) ∧ (¬x2,1,C V p2,1 V y2,1,1) ∧ 
(¬x2,1,C V ¬p2,1 V y2,1,2) ∧ (¬x2,1,C V p2,1 V ¬y2,1,2) ∧ 
(¬x2,1,C V ¬p2,1 V y2,1,3) ∧ (¬x2,1,C V p2,1 V ¬y2,1,3) ∧ 

(¬x2,2,A V ¬p2,2 V ¬y2,2,1) ∧ (¬x2,2,A V p2,2 V y2,2,1) ∧ 
(¬x2,2,A V ¬p2,2 V y2,2,2) ∧ (¬x2,2,A V p2,2 V ¬y2,2,2) ∧ 
(¬x2,2,A V ¬p2,2 V ¬y2,2,3) ∧ (¬x2,2,A V p2,2 V y2,2,3) ∧ 

(¬x2,2,B V ¬p2,2 V y2,2,1) ∧ (¬x2,2,B V p2,2 V ¬y2,2,1) ∧ 
(¬x2,2,B V ¬p2,2 V ¬y2,2,2) ∧ (¬x2,2,B V p2,2 V y2,2,2) ∧ 
(¬x2,2,B V ¬p2,2 V y2,2,3) ∧ (¬x2,2,B V p2,2 V ¬y2,2,3) ∧ 

(¬x2,2,C V ¬p2,2 V ¬y2,2,1) ∧ (¬x2,2,C V p2,2 V y2,2,1) ∧ 
(¬x2,2,C V ¬p2,2 V y2,2,2) ∧ (¬x2,2,C V p2,2 V ¬y2,2,2) ∧ 
(¬x2,2,C V ¬p2,2 V y2,2,3) ∧ (¬x2,2,C V p2,2 V ¬y2,2,3)

(7.9)
Equivalência para deixar na FNC ---------------------------------------
xi,j,* -> yi,j,w ≡ ¬xi,j,* V yi,j,w
-----------------------------------------------------------------------
(¬x1,1,* V y1,1,1) ∧ (¬x1,1,* V y1,1,2) ∧ (¬x1,1,* V y1,1,3) ∧ 

(¬x1,2,* V y1,2,1) ∧ (¬x1,2,* V y1,2,2) ∧ (¬x1,2,* V y1,2,3) ∧ 

(¬x2,1,* V y2,1,1) ∧ (¬x2,1,* V y2,1,2) ∧ (¬x2,1,* V y2,1,3) ∧ 

(¬x2,2,* V y2,2,1) ∧ (¬x2,2,* V y2,2,2) ∧ (¬x2,2,* V y2,2,3)

(7.10)
(¬z1,1 V y1,1,1) ∧ (¬z1,1 V y1,2,1) ∧ (z1,1 V ¬y1,1,1 V ¬y1,2,1) ∧ 
(¬z1,2 V y1,1,2) ∧ (¬z1,2 V y1,2,2) ∧ (z1,2 V ¬y1,1,2 V ¬y1,2,2) ∧ 
(¬z1,3 V y1,1,3) ∧ (¬z1,3 V y1,2,3) ∧ (z1,3 V ¬y1,1,3 V ¬y1,2,3) ∧ 

(¬z2,1 V y2,1,1) ∧ (¬z2,1 V y2,2,1) ∧ (z2,1 V ¬y2,1,1 V ¬y2,2,1) ∧ 
(¬z2,2 V y2,1,2) ∧ (¬z2,2 V y2,2,2) ∧ (z2,2 V ¬y2,1,2 V ¬y2,2,2) ∧ 
(¬z2,3 V y2,1,3) ∧ (¬z2,3 V y2,2,3) ∧ (z2,3 V ¬y2,1,3 V ¬y2,2,3)

(7.11)
(z1,2 V z2,2)

(7.12)
(¬z1,1) ∧ (¬z2,1) ∧

(¬z1,3) ∧ (¬z2,3)
'''

In [ ]:
'''
(7.5-7.6) <hard>
Força que exista apenas um xi,j,t verdadeiro para o literal j 
na cláusula i

(7.5.1) <<1>>
Força que exista o mínimo de literais possível em uma cláusula

(7.7) <<hard>>
Força que cada cláusula possua pelo menos um literal

(7.8) <<hard>>
...

(7.9) <<hard>>
Força que os resultados das cláusulas conjuntivas não sejam
interferidos por literais ignorados

(7.10) <<weight>>
Força que os resultados das cláusulas conjuntivas batam com
as classes/predições

(7.11-7.12) <<weight>>
Força que o resultado da cláusula i seja consistente com a
classe/predição da instância w 
'''

# Model Tests

In [33]:
import sys, os
if not sys.path[0] == os.path.abspath('..'):
    sys.path.insert(0, os.path.abspath('..'))

import pandas as pd
import numpy as np
from models.lqdnfmaxsat import LQDNFMaxSAT
from sklearn.model_selection import train_test_split


Xy = pd.read_csv('../databases/monography_example.csv')

X = Xy.drop(['Divida'], axis=1)
y = Xy['Divida']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [46]:
model = LQDNFMaxSAT(
    max_rule_set_size=2,
    max_size_each_rule=3,
    categorical_columns_index=[2],
    number_quantiles_ordinal_columns=4,
    number_lines_per_partition=3,
    rules_accuracy_weight=10,
    balance_instances=True
)

model.fit(X, y)
# model.fit(X_train, y_train)

In [47]:
model.get_rules()

'(Not Escolaridade Medio and Salario <= 5879.5)'

In [48]:
model.score(X, y)
# model.score(X_test, y_test)

0.6666666666666666

In [31]:
model.get_total_time_solver_solutions()

0.0

In [32]:
print('Rule set size:', model.get_rule_set_size())
print('Larger rule size:', model.get_larger_rule_size())

Rule set size: 2
Larger rule size: 3


In [8]:
model.get_dataset_binarized().get_classes(1)

array([1, 1, 0, 1, 0, 0], dtype=int64)

In [6]:
model.get_dataset_binarized().get_normal_features_label()

<PandasArray>
[        'Sexo Feminino',     'Escolaridade Fund',    'Escolaridade Medio',
 'Escolaridade Superior',    'Salario <= 3603.75',     'Salario <= 5879.5',
    'Salario <= 7216.25']
Length: 7, dtype: object

In [8]:
model.get_dataset_binarized().get_normal_instances(1)

array([[1, 0, 0, 1, 1, 1, 1],
       [0, 0, 1, 0, 0, 1, 1],
       [1, 1, 0, 0, 0, 0, 0],
       [1, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 1],
       [0, 0, 1, 0, 1, 1, 1]], dtype=int64)

# WCNF, IDPool and RC2 libs tests

In [1]:
from pysat.formula import WCNF      # https://pysathq.github.io/docs/html/api/formula.html#pysat.formula.WCNF
from pysat.formula import IDPool    # https://pysathq.github.io/docs/html/api/formula.html#pysat.formula.IDPool
from pysat.examples.rc2 import RC2

In [2]:
formula = WCNF()

formula.append([1, -2])                             # (A V ¬B)∞ ∧
formula.extend([[2], [-1, 3]], weights=[10, 8])     # (B)10 ∧ (¬A V C)8 ∧
formula.append([-3])                                # (¬C)∞
print('Soft clauses:', formula.soft)
print('Hard clauses', formula.hard)
formula.to_file('wcnf_draft.wcnf')

Soft clauses: [[2], [-1, 3]]
Hard clauses [[1, -2], [-3]]


In [3]:
literals = IDPool()
S = lambda i, j: literals.id(f'S{i}{j}')

S(1, 1)     # create literal 1
S(1, 2)     # create literal 2
-S(1, 1)    # use literal 1, but negated (-)

-1

In [20]:
formula = WCNF()
formula.extend([[1], [1]], weights=[0, 0])
solver = RC2(formula)
solver_solution = solver.compute()
solver.oracle_time()
type(solver_solution)

list

# Binarize class tests

In [1]:
import pandas as pd
import numpy as np

Xy = pd.read_csv('../databases/monography_example.csv')

X = Xy.drop(['Divida'], axis=1)
y = Xy['Divida']

In [2]:
X

Idade       Sexo Escolaridade  Salario
0     26   Feminino     Superior      787
1     26  Masculino        Medio     5415
2     26   Feminino         Fund     7507
3     26   Feminino     Superior     7560
4     26  Masculino     Superior     6344
5     26  Masculino        Medio     3000

In [16]:
import sys, os
if not sys.path[0] == os.path.abspath('..'):
    sys.path.insert(0, os.path.abspath('..'))

from utils.binarize import Binarize

data = Binarize(
    data_frame=X,
    series=y,
    categorical_columns_index=[2],
    number_quantiles_ordinal_columns=5,
    number_partitions=2,
    balance_instances=True,
    balance_instances_seed=21
)

In [17]:
for partition in data.get_classes():
    print(partition)

[1 0 0]
[1 1 0]


In [6]:
data.get_normal_features_label()

<PandasArray>
[        'Sexo Feminino',     'Escolaridade Fund',    'Escolaridade Medio',
 'Escolaridade Superior',     'Salario <= 3000.0',     'Salario <= 5415.0',
     'Salario <= 6344.0',     'Salario <= 7507.0']
Length: 8, dtype: object

In [7]:
data.get_opposite_features_label()

<PandasArray>
[           'Sexo Masculino',     'Not Escolaridade Fund',
    'Not Escolaridade Medio', 'Not Escolaridade Superior',
          'Salario > 3000.0',          'Salario > 5415.0',
          'Salario > 6344.0',          'Salario > 7507.0']
Length: 8, dtype: object

In [17]:
X_norm = data.get_normal_instances()
X_norm

[array([[1, 1, 0, 0, 0, 0, 0, 1],
        [0, 0, 0, 1, 0, 0, 1, 1],
        [1, 0, 0, 1, 0, 0, 0, 0],
        [0, 0, 1, 0, 0, 1, 1, 1],
        [0, 0, 1, 0, 1, 1, 1, 1],
        [1, 0, 0, 1, 1, 1, 1, 1]], dtype=int64)]

In [9]:
X_oppo = data.get_opposite_instances()
X_oppo

[array([[0, 1, 1, 0, 0, 0, 0, 0],
        [1, 1, 0, 1, 0, 0, 0, 0]], dtype=int64),
 array([[0, 0, 1, 1, 1, 1, 1, 0],
        [0, 1, 1, 0, 1, 1, 1, 1]], dtype=int64),
 array([[1, 1, 0, 1, 1, 0, 0, 0],
        [1, 1, 1, 0, 1, 1, 0, 0]], dtype=int64)]

# Instances class distribution by class

In [66]:
classes = data.get_classes()
for i, classes_partition in enumerate(classes):
    print(f'Classes Partition {i+1}:')
    print(f'0: {len(classes_partition[classes_partition == 0])}')
    print(f'1: {len(classes_partition[classes_partition == 1])}')

Classes Partition 1:
0: 5
1: 3
Classes Partition 2:
0: 5
1: 3
Classes Partition 3:
0: 5
1: 3
Classes Partition 4:
0: 5
1: 3
Classes Partition 5:
0: 5
1: 3
Classes Partition 6:
0: 5
1: 3
Classes Partition 7:
0: 5
1: 3
Classes Partition 8:
0: 6
1: 2
Classes Partition 9:
0: 5
1: 3
Classes Partition 10:
0: 6
1: 2
Classes Partition 11:
0: 5
1: 2
Classes Partition 12:
0: 5
1: 2
Classes Partition 13:
0: 5
1: 2
Classes Partition 14:
0: 5
1: 2
Classes Partition 15:
0: 5
1: 2
Classes Partition 16:
0: 5
1: 2
Classes Partition 17:
0: 4
1: 3
Classes Partition 18:
0: 5
1: 2
Classes Partition 19:
0: 4
1: 3
Classes Partition 20:
0: 5
1: 2


In [24]:
np.where(classes[1] == 1)

(array([0], dtype=int64),)

In [10]:
data.get_qtt_binarized_feat_per_original_feat()

<IntegerArray>
[0, 1, 3, 4]
Length: 4, dtype: Int64